# Generated by Django 3.2.7 on 2021-09-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'CENTIMETERS'), ('m', 'METERS'), ('in', 'INCHES')], default='cm', max_length=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='lost_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lost_team', to='api.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('RS', 'ROUND_OF_SIXTEEN'), ('QF', 'QUARTER_FINAL'), ('SF', 'SEMI_FINAL'), ('GF', 'GRAND_FINAL')], max_length=3),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='winner_team', to='api.team'),
        ),
    ]
