# Generated by Django 3.2.7 on 2021-09-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210914_2007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchplayerstat',
            unique_together={('match', 'player')},
        ),
    ]
