# Generated by Django 3.2.7 on 2021-09-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_matchplayerstat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nic',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
